### ISSUE TITLE
And where is the documentation for the package

### ISSUE THREAD

**Issue by andryshok** [thejacer87/php-canadapost-api#27]
And where is the documentation for the package? As to use it?
composer remove  thejacer87/canadapost-api

**Comment by thejacer87** [comment]
not 100% sure what you're asking. to install it, the command is in the readme `composer require thejacer87/canadapost-api`

**Comment by andryshok** [comment]
How do I use the library? Methods? Functions?

**Comment by thejacer87** [comment]
ya sorry man. this was a package i created for work/specific client. as with most projects at work, documentation can be left to last lol. best advice i can give is to just look into the code (and tests) to see how the methods are called. if you're able to decipher it, feel free to create a PR and add to the README :)

i've since moved cities and companies. and don't plan to necessarily keep this package updated

if you would like help getting this implemented you can send me and email and we could discuss rates. or i could pass you along to the company i used to work at if you would prefer them (although their company rate is like >$200USD/hr when i was there last). 

as far as i know this is being used in a production site. so it should be usable for you assuming you need basic usage.

**Comment by thejacer87** [comment]
@andryshok forgot about this: https://github.com/thejacer87/commerce_canadapost

this is the drupal module we made that used this API, so you can checkout that code to see how things get setup and call the CP API
